export type Lang = "vi" | "en";

export const copy = {
  vi: {
    langLabel: "VI",
    otherLang: "EN",
    badge: "Feedback từ Anh/Chị",
    landingTitle: "Cảm ơn Anh/Chị đã sử dụng CP KPI Dashboard",
    landingSub:
      "Những góp ý của Anh/Chị sẽ giúp team hiểu điểm nào đang hoạt động tốt và điểm nào cần cải thiện, để Dashboard ngày càng hữu ích hơn cho các kỳ cập nhật tiếp theo.",
    cardBugTitle: "Báo lỗi nhanh",
    cardBugDesc: "Gặp lỗi cần team kiểm tra ngay? Gửi cho team biết.",
    cardBugCta: "Báo lỗi",
    cardFbTitle: "Chia sẻ cảm nhận",
    cardFbDesc: "Cho team biết trải nghiệm dùng Dashboard — chỉ mất 2 phút.",
    cardFbCta: "Gửi feedback",
    cardTrainingTitle: "Feedback về buổi training",
    cardTrainingDesc: "Cho team biết cảm nhận của Anh/Chị sau buổi training hôm nay.",
    cardTrainingCta: "Gửi feedback training",
    contactLabel: "Liên hệ để hỗ trợ:",
    contactPeople: "YenLH5 · TraLT",
    back: "Quay lại",
    next: "Tiếp theo",
    submit: "Gửi phản hồi",
    submitBug: "Gửi báo lỗi",
    submitting: "Đang gửi…",
    optional: "(không bắt buộc)",
    thanksTitleFb: "Cảm ơn Anh/Chị rất nhiều! 🙏",
    thanksSubFb:
      "Mỗi góp ý của Anh/Chị đều được team đọc và cân nhắc kỹ để Dashboard ngày càng thuận tiện và hữu ích hơn trong các kỳ cập nhật tiếp theo.",
    thanksTitleBug: "Đã ghi nhận báo lỗi! 🛠",
    thanksSubBug:
      "Team sẽ kiểm tra và phản hồi Anh/Chị sớm nhất có thể.\nCảm ơn Anh/Chị đã gửi thông tin.",
    thanksTitleTraining: "Cảm ơn Anh/Chị rất nhiều! 🎓",
    thanksSubTraining:
      "Feedback của Anh/Chị sẽ giúp team cải thiện các buổi training tiếp theo. Nếu Anh/Chị cần hỗ trợ thêm, team sẽ liên hệ sớm.",
    thanksBack: "Về trang đầu",
    errorGeneric: "Có lỗi xảy ra, Anh/Chị vui lòng thử lại.",

    tabALabel: "A. Cảm nhận chung",
    tabBLabel: "B. Chi tiết",
    tabASub: "Đôi nét về Anh/Chị và cảm nhận tổng thể sau khi dùng Dashboard.",
    tabBSub: "Các câu hỏi chi tiết hơn về trải nghiệm sử dụng — tất cả đều không bắt buộc.",

    q_dept: "Domain của Anh/Chị",
    q_dept_ph: "Ví dụ: HR, S&I, DTO…",
    q_overall:
      "Nhìn chung, Anh/Chị thấy việc sử dụng Dashboard trong kỳ cập nhật vừa rồi có dễ dàng và thuận tiện không?",
    q_overall_feedback: "Chia sẻ trải nghiệm của Anh/Chị",
    q_overall_feedback_ph: "Chia sẻ trải nghiệm của Anh/Chị…",

    q_start_clarity: "Khi bắt đầu cập nhật, Anh/Chị có nhanh chóng biết mình cần làm gì và bắt đầu từ đâu không?",
    q_clarity_kpi: "Anh/Chị có dễ xác định thông tin cần nhập cho từng loại KPI không?",
    q_clarity_score: "Cách hệ thống tính điểm KPI và tổng hợp kết quả phòng ban có dễ hiểu không?",
    q_change_flow: "Khi cần thêm KPI hoặc Milestone mới, các bước thực hiện có rõ ràng, thuận tiện không?",
    q_support_clarity: "Khi gặp khó khăn, Anh/Chị có dễ biết cần hỏi ai hoặc tìm hướng dẫn ở đâu không?",
    q_time_saved:
      "So với cách báo cáo trước đây, Dashboard có giúp Anh/Chị tiết kiệm thời gian và nắm rõ tình hình phòng ban hơn không?",
    q_change_note: "Anh/Chị có góp ý gì để cải thiện Dashboard?",
    q_change_note_ph: "Chia sẻ thêm nếu có…",

    trainingTitle: "Feedback về buổi training",
    trainingSub: "Team cần vài phút để hiểu buổi training hôm nay đã giúp ích thế nào. Cảm ơn Anh/Chị.",
    tr_features_question: "Trong buổi hôm nay, Anh/Chị thấy các tính năng sau dễ sử dụng đến mức nào?",
    tr_feature_submit_results: "Submit Results (nhập & nộp kết quả)",
    tr_feature_edit_kpis: "Edit KPIs (gửi change request)",
    tr_feature_dept_scorecard: "Dept Scorecard (xem điểm phòng)",
    tr_feature_kira: "Kira (hỏi–đáp AI)",
    tr_support_question: "Anh/Chị có muốn được hỗ trợ 1:1 thêm về cách sử dụng app sau buổi hôm nay không?",
    tr_support_yes: "Có cần",
    tr_support_no: "Không cần",
    tr_support_areas_question: "Anh/Chị mong được hỗ trợ thêm ở phần nào? (chọn nhiều)",
    tr_support_areas_opts: [
      "Đăng nhập/truy cập",
      "Submit Results",
      "Edit KPIs / change request",
      "Dept Scorecard",
      "Kira",
      "Khác",
    ],
    tr_support_other_ph: "Chi tiết Anh/Chị cần hỗ trợ thêm…",
    tr_pain_point: "Khó khăn hoặc thắc mắc lớn nhất của Anh/Chị là gì?",
    tr_pain_point_ph: "Chia sẻ thêm nếu có…",

    bugTitle: "Báo lỗi nhanh",
    bugSub: "Team cần vài thông tin để tái tạo và xử lý lỗi nhanh nhất. Cảm ơn Anh/Chị.",
    bug_issue: "Anh/Chị đang gặp vấn đề gì?",
    bug_issue_ph: "Mô tả ngắn gọn điều xảy ra — càng cụ thể càng tốt.",
    bug_where: "Xảy ra ở màn hình nào? (chọn nhiều nếu cần)",
    bug_where_opts: [
      "Submit Results",
      "Edit KPIs",
      "Dashboard",
      "Kira",
      "Notifications",
      "Đăng nhập / Truy cập",
      "Khác",
    ],
    bug_screenshot: "Đính kèm ảnh chụp màn hình",
    bug_screenshot_optional: "(không bắt buộc)",
    bug_screenshot_uploading: "Đang tải ảnh lên…",
    bug_screenshot_error: "Tải ảnh lên thất bại, vui lòng thử lại.",
    bug_screenshot_remove: "Xóa ảnh",
    bug_screenshot_toolarge: "Ảnh vượt quá 10MB.",
    bug_screenshot_badtype: "Chỉ nhận file PNG hoặc JPG.",
    bug_screenshot_hint: (n: number) => `PNG / JPG · ≤10MB mỗi ảnh · Tối đa ${n} ảnh`,
    bug_screenshot_limit: (n: number) => `Anh/Chị chỉ có thể đính kèm tối đa ${n} ảnh.`,
    bug_domain: "Domain của Anh/Chị để team hỗ trợ thêm",
    bug_domain_ph: "Ví dụ: HR, S&I, DTO…",

    scaleEase: [
      { v: 1, e: "😣", label: "Rất khó" },
      { v: 2, e: "🙁", label: "Khó" },
      { v: 3, e: "😐", label: "Bình thường" },
      { v: 4, e: "🙂", label: "Dễ" },
      { v: 5, e: "😄", label: "Rất dễ" },
    ],
    scaleClarity: [
      { v: 1, e: "😣", label: "Rất khó hiểu" },
      { v: 2, e: "🙁", label: "Chưa rõ" },
      { v: 3, e: "😐", label: "Bình thường" },
      { v: 4, e: "🙂", label: "Rõ" },
      { v: 5, e: "😄", label: "Rất rõ" },
    ],
    scaleStartClarity: [
      { v: 1, e: "😣", label: "Rất mơ hồ" },
      { v: 2, e: "🙁", label: "Mơ hồ" },
      { v: 3, e: "😐", label: "Bình thường" },
      { v: 4, e: "🙂", label: "Rõ ràng" },
      { v: 5, e: "😄", label: "Rất rõ ràng" },
    ],
    scaleHelpful: [
      { v: 1, e: "😣", label: "Không giúp ích gì" },
      { v: 2, e: "🙁", label: "Ít giúp ích" },
      { v: 3, e: "😐", label: "Bình thường" },
      { v: 4, e: "🙂", label: "Có giúp ích" },
      { v: 5, e: "😄", label: "Giúp ích nhiều" },
    ],
    scaleEaseSkip: [
      { v: 1, e: "😣", label: "Rất khó" },
      { v: 2, e: "🙁", label: "Khó" },
      { v: 3, e: "😐", label: "Bình thường" },
      { v: 4, e: "🙂", label: "Dễ" },
      { v: 5, e: "😄", label: "Rất dễ" },
      { v: 0, e: "➖", label: "Chưa thử" },
    ],
  },
  en: {
    langLabel: "EN",
    otherLang: "VI",
    badge: "Your feedback",
    landingTitle: "Thank you for taking the time to use the CP KPI Dashboard",
    landingSub:
      "Your feedback will help the team understand what's working well and what needs improvement, so the Dashboard becomes more useful for the coming update cycles.",
    cardBugTitle: "Report a bug",
    cardBugDesc: "Something not working? Let the team know.",
    cardBugCta: "Report a bug",
    cardFbTitle: "Share feedback",
    cardFbDesc: "Tell the team how the Dashboard felt to use — just 2 minutes.",
    cardFbCta: "Give feedback",
    cardTrainingTitle: "Training session feedback",
    cardTrainingDesc: "Tell the team how you felt about today's training session.",
    cardTrainingCta: "Give training feedback",
    contactLabel: "Reach out for support:",
    contactPeople: "YenLH5 · TraLT",
    back: "Back",
    next: "Next",
    submit: "Send feedback",
    submitBug: "Send bug report",
    submitting: "Sending…",
    optional: "(optional)",
    thanksTitleFb: "Thank you so much! 🙏",
    thanksSubFb:
      "Every piece of feedback is read and carefully considered so the Dashboard becomes more convenient and useful in the coming cycles.",
    thanksTitleBug: "Bug logged 🛠",
    thanksSubBug:
      "The team will look into this and get back to you soon.\nThanks for sending the information.",
    thanksTitleTraining: "Thank you so much! 🎓",
    thanksSubTraining:
      "Your feedback will help the team improve future training sessions. If you need extra support, the team will reach out soon.",
    thanksBack: "Back to start",
    errorGeneric: "Something went wrong, please try again.",

    tabALabel: "A. Overall feel",
    tabBLabel: "B. Details",
    tabASub: "A few details about you and your overall experience.",
    tabBSub: "More detailed questions about your experience — all optional.",

    q_dept: "Your domain",
    q_dept_ph: "E.g. HR, S&I, DTO…",
    q_overall: "Overall, was using the Dashboard this update cycle easy and convenient?",
    q_overall_feedback: "Share your experience",
    q_overall_feedback_ph: "Share your experience…",

    q_start_clarity: "When you started updating, did you quickly know what to do and where to begin?",
    q_clarity_kpi: "Was it easy to figure out what information to enter for each KPI type?",
    q_clarity_score: "Was it clear how the system computes KPI scores and rolls them up to department results?",
    q_change_flow: "When adding a new KPI or Milestone, were the steps clear and convenient?",
    q_support_clarity: "When you ran into trouble, was it easy to know who to ask or where to find guidance?",
    q_time_saved:
      "Compared to the previous reporting method, does the Dashboard help you save time and stay on top of your department's status?",
    q_change_note: "Any suggestions to improve the Dashboard?",
    q_change_note_ph: "Share more if you'd like…",

    trainingTitle: "Training session feedback",
    trainingSub: "A few minutes to understand how helpful today's training session was. Thank you.",
    tr_features_question: "In today's session, how easy did you find the following features to use?",
    tr_feature_submit_results: "Submit Results (entering & submitting results)",
    tr_feature_edit_kpis: "Edit KPIs (submitting change requests)",
    tr_feature_dept_scorecard: "Dept Scorecard (viewing department scores)",
    tr_feature_kira: "Kira (AI Q&A)",
    tr_support_question: "Would you like additional 1:1 support on using the app after today's session?",
    tr_support_yes: "Yes, please",
    tr_support_no: "No, thanks",
    tr_support_areas_question: "Which areas would you like more support on? (pick any)",
    tr_support_areas_opts: [
      "Sign-in / Access",
      "Submit Results",
      "Edit KPIs / change request",
      "Dept Scorecard",
      "Kira",
      "Other",
    ],
    tr_support_other_ph: "Details on what you need help with…",
    tr_pain_point: "What's your biggest difficulty or question?",
    tr_pain_point_ph: "Share more if you'd like…",

    bugTitle: "Report a bug",
    bugSub: "A few details help the team reproduce and fix it faster. Thank you.",
    bug_issue: "What's the problem?",
    bug_issue_ph: "A short description of what happened — the more specific, the better.",
    bug_where: "Where did it happen? (pick any)",
    bug_where_opts: [
      "Submit Results",
      "Edit KPIs",
      "Dashboard",
      "Kira",
      "Notifications",
      "Sign-in / Access",
      "Other",
    ],
    bug_screenshot: "Attach a screenshot",
    bug_screenshot_optional: "(optional)",
    bug_screenshot_uploading: "Uploading…",
    bug_screenshot_error: "Upload failed, please try again.",
    bug_screenshot_remove: "Remove",
    bug_screenshot_toolarge: "Image is larger than 10MB.",
    bug_screenshot_badtype: "Only PNG or JPG files are accepted.",
    bug_screenshot_hint: (n: number) => `PNG / JPG · ≤10MB each · Up to ${n} images`,
    bug_screenshot_limit: (n: number) => `You can attach up to ${n} images.`,
    bug_domain: "Your domain so the team can follow up",
    bug_domain_ph: "E.g. HR, S&I, DTO…",

    scaleEase: [
      { v: 1, e: "😣", label: "Very hard" },
      { v: 2, e: "🙁", label: "Hard" },
      { v: 3, e: "😐", label: "Neutral" },
      { v: 4, e: "🙂", label: "Easy" },
      { v: 5, e: "😄", label: "Very easy" },
    ],
    scaleClarity: [
      { v: 1, e: "😣", label: "Very unclear" },
      { v: 2, e: "🙁", label: "Unclear" },
      { v: 3, e: "😐", label: "Neutral" },
      { v: 4, e: "🙂", label: "Clear" },
      { v: 5, e: "😄", label: "Very clear" },
    ],
    scaleStartClarity: [
      { v: 1, e: "😣", label: "Very unclear" },
      { v: 2, e: "🙁", label: "Unclear" },
      { v: 3, e: "😐", label: "Neutral" },
      { v: 4, e: "🙂", label: "Clear" },
      { v: 5, e: "😄", label: "Very clear" },
    ],
    scaleHelpful: [
      { v: 1, e: "😣", label: "Not helpful at all" },
      { v: 2, e: "🙁", label: "Slightly helpful" },
      { v: 3, e: "😐", label: "Neutral" },
      { v: 4, e: "🙂", label: "Helpful" },
      { v: 5, e: "😄", label: "Very helpful" },
    ],
    scaleEaseSkip: [
      { v: 1, e: "😣", label: "Very hard" },
      { v: 2, e: "🙁", label: "Hard" },
      { v: 3, e: "😐", label: "Neutral" },
      { v: 4, e: "🙂", label: "Easy" },
      { v: 5, e: "😄", label: "Very easy" },
      { v: 0, e: "➖", label: "Haven't tried" },
    ],
  },
} as const;

export type Copy = typeof copy["vi"];
